name: Maintain Blacklist

on:
  push:
  pull_request:

jobs:
  maintain:
    name: Maintain Blacklist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Scripts
        run: ./maintain.sh

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Blacklist maintenance
          branch: ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
